apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sapfire-prod
resources:
  - ../../base
  - namespace.yaml
  # - sealed-secrets   # uncomment once populated, see sealed-secrets/README.md
patches:
  - path: patch-issuer.yaml
  - path: patch-scale.yaml
  - path: patch-storage.yaml
images:
  - name: sapfire/client
    newTag: latest
  - name: sapfire/server
    newTag: latest
  - name: sapfire/keycloak
    newTag: latest
