---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_DB_PASSWORD: AgAOECB5l+OmY01DS0F0mW0EzTx8ZgBUiWnWvaABrWMa6zUlpSG4Rco+p1Zf8SowIwUdOOGlH/G/kyIHfm1sLqfVPtikt0TPq6svNbiBWErzIcpxTXZgAHOvPRx2KAHgGhTfKkfjkPN8l8UCNzK5VLJTU6w0HyCpbaUBvxE1fupU/GI5omUdC+zH+wC1juLnqRSsnsbAmBhYgbdZhxcj+PxlBunVfUwNfS+jUa0kyPemTIspr+Bv6vlx6Np9gIXhTVb/8E/c9ju8Sek9EbSJErY3TRugsHutEMgvXGPVxpsWNf4ObjUJ3kJaJ3ZyisWevgeLTFd8eyFSfy71kMoRX8MMM1GbHQGYMftWl/G8mreK00CD4MYjC8jQeYzGzV/wztNysDjUJvVoX3sdzHaEiLXDxA0UykbemEf/dlTPpn8YEdUUGfS4AUMUTjw/bMk8FEp40XoiLyuY5QQfF/j2VooQTUf3AMuzJBrQMIMSpx3VbOI6DgiObCLMiF8ynAZU7YkGnyuV3+VNTqn1Sqy7MIGQoG8AYVbDbGmx2I9+LwbZDf/jbrPonXV+OzkWo0iivWb8KJFzqNIE5ONGlXCRBvp5fP1Tx0WIhrtsOwqFV3CuKYcCHDsT2g25AZ3gMJsXW4XjRx/FjZYLb7osWsPctWet6bN7w2WeLPujmnclaCqkTMScBPkKYho/gKw61YuxvvPmmChAseKnUz9tttCDm7TBG2iB4N4vADdgNNSco9N8uQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: sapfire-dev
