---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgBe3j/CT+65RC42QUdNzRMdkoJk9ug/4SGsJb9hkH11YxWdSBTiSrz/cvflyooC5IXpCHeElSSl3T8vYDik71TCD/EZY75wHXVXpVPJhiBBs2XJo1Wv2I5VDStZYxKSTevOeuxKWJp6hH3VYMevlIxQ4gQjWt9LgMeSbhGtK/vmo+dblvNv/N+KVhT06/JJ6TzeXxJhhbALGXI5tRUv3cCWs/nXz3WRCOGmrooebmcjvLGITlVDPlZqtN/KO0ADl4hQqJmoKByrIaSPzOaFsOjj0pcqWCPGgQnmCAslP/MjfdUArHQX3sum7BdRzLcWdaDNBfSJTgkfA6e0+1deMmKwq2RBQ2QgqynL5recNM2luU/awYEjNp2fFr1srtNVw8tsAZhv/mnIITsE3l5c72He6fNUj/+PiDlB/Zal2ALtIKXfKLs0j+Z8IgPBWyGiUKeob3zrfaAEOHBcN+GP+S+NGXpb5YZroce78UHir9EMz89MAwo3+PlBFOcfu8jBY2GDCYgxwG1ZvFF6yG7JdTBVaEjJ8vYyeYRaUKpY/bs3BjJfI/eCXmD+5sH0FGpgRSukoF4iZ8HChq82N4q5V0X1vspH2JXxHd9YuHBLezht0M6asoXTb2ABXypLDZ0/LJGUvRhqAOLURz8nLNZamo9tEP9ApYtl5MaBos48rYt00FGp4EY8epP3qqXbV8EUtLdF8xvMAL9BlTufDTRA9jM9/7sm4CjDgV/r7ngB4G7uuw==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: sapfire-dev
