---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_DB_PASSWORD: AgBqliqn8PYFSpypwq+mXCgzDMQQeXECMtNyFY888UsFBxIZmPUUkkvdwNhgPeRnMx9fohxvf5itrm1NX+8c59rbs737Y34gPb6YsKsBN03+rpb0J28sgSorR2Qg1iwHbNkUnZ+eviRNpBj8WtlyF4lh3k2jUzaCdKPkae+neXKDKVGwLnFTMNrivb4zZAijUMXiAcASj0LPA2bzJ1Um6CFqisrrP8flaOjNvwpM9a6wonM7KDO2fF1g+YDmmQ73xE3bR3ELZGtk6mTdEVPHZWQa3YifprPBprnmVg6qGj5r6uWgjfQ97G9pF/VN7EhJu/18MULBew3jfN9CgaQos5jI5TtDvDBqJ6wPk98LYpHjdsPTjIzmpKorylcXK+S35O6+J2tn1o5w3UWmBSsRMvj+EZ5oF4VcbDzzl9IfTMpcrmi1f3bzEuFUO6zjfsEgUtSWyxtQ/d/iU6mXRT1RVOA5esAITQ7NX60MV3XF6fjPkDcqqI98kG+iXglS0CHJMZyp/zPUtZNmu/wiRybRchgJ85GxnuVaeUysRvJnKtvAgwTcjhOjAk/hHh4WikVI/IHFPjcs6FEUSIM9PyTZR/H7bssEkdRlMrg7z3CgOXh7TF4XrhP+6kZPOrj1lICTBvaeUxUqrhPLRvZFa781kxeCFeLjsMoQPYt62bOxsDWRcdgYjpmR6pVVsC9JM58DvLaOd5NGN+ylNh3Xx327lecKs8ylVk/ICJ+r4wCV/2Pivw==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: sapfire-dev
