---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client-secret
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_ADMIN_CLIENT_SECRET: AgAGBWAm7ZLu85Bptpddaskw4HDWwHML98erX2NrdcX/bYBHt4Ar75+DKRztYibyzxBxA8DzHcoVspKynA/RKfOe+z8eNDt+JX2h3EsTY+9mKwZSbRoyeqGIyqEm1LvXV0R8onZ1XO7jTRV7qcahFCN/fOqC9GEmQ2ZIQpVKuQwv4bJkhCsk5179FmnUQ+FzRE6Wp9LmGl5HYH5KZSg25SvfnVKHC4E/g3BKDTvNd0/f1b6xDCr85bWiyb+/dA+mMYFu2BXPVWw/G41xDO+LOI15J5M6VGZFkxflQJ5+j7TkmQdK2yTBJSHbWmox8tnR4JwXj6ST/XPeSnW4o2HbRgFa9zIgTdSkjYAY/0x9i10nLMyC1Fz2QxgczudjVjtG6Ae1s9WbIYAMe6n4g8TQX7Qhu94bB2553TGWP8nICUOTUlrECvhPaNBkJUJoA4qYFciG+CwYXsLRcuFwwa2NJ+retHtseQ92E8jAofblsbfTRXX/lXZehra6yK7s9HzMR6R4nLGEKCQCm6zh6BqH8wJRxXAZYbzky8hH61ygVxcB8JUAb/NJ3hPz2P4h4GubmvTdHPCCvWAAVBpYBZp3RxuFPazqu6jZued/fFEcqRCU6csG1XesGB8LW82pHS227QYIhCgVM7cSXCj9MyBQuIfJGxyFlA/6WcxXka0vEU78FdjZKBsQ7BjkvHrLXSuRles9k5PhNQhPjpwfjueYvbNCS0dhSJYJ1bMzvZJZM3uY8w==
  template:
    metadata:
      name: keycloak-client-secret
      namespace: sapfire-dev
