---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-client-secret
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_ADMIN_CLIENT_SECRET: AgBLT4LyoXA4LZe0snxu8nF6KtQZFR7mcARX0YATckhVrsC2y3tjWiwWPFtcfpfJ/JSfq+6XWO6szWfSMI8fsSmkULYMmcGk37E5s0vBIbYIU9bUk8k1gmV8MD/H4Vr/d45myE5FNU7pvODYb8PBldC68g3RMyNPNBtK2ruLMRjuZ0mi6PEx7v1Vb8nPQ9dM6r9BZ/IKklC5Dwq5nl4zV6xMUsVpFf8+VZo6vuecmLL0gtOI6o0Q5sMd4zLkty10J1yiTzYwCWHbUwVZ8u1u5hJV1ZaUuQQM1jHiyZ0/3GE+HWSpF8zK2Xf1Oec3yQsAcKXZcl8tKGwPxm3g1VaUn0aopYWAq1mCeKUj4taaNKBwZrNuA/YvWFITxw9U1SudvmQt0PEHJ0lYVaORvXVwFc3KiIDAkKu79DdEUzsfNptMnNrp2uCxYAY4nONxvQiX2EOQ0aCMrgl9/4qIUUsVFYYdqnKx91oNKoDAz62erGMU/RERwhEfVZApcQ85ilDGOumEdq4EFs9Yp4ieTruDQzgqADdd7nlVnxR5WCak6hON1z9upu21eX0RSEmv+2GC+6FTJ7Br62kajKDioHZWzABdpfukLat3Xd2JP9r5Ji0+8w+KAnsPEecY6UWvbx4eM5hCrVgQm6mwBqeahQSc+pENBgiNB1FRC0MGxJV6XcmqPg1ltHlXU8nFzegZLFjPyZSsvkNLNLyPmq62DB/MFFljEAWLVetnhT6fLe2bkrxquA==
  template:
    metadata:
      name: keycloak-client-secret
      namespace: sapfire-dev
