---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgAXqpIN3X8mMZTWCwJMtW7HJ9Ets6g6pd83Mk7alAuVnFzeBGE1Y5T2H5Z0Mm1oFp+19aOJrdYQDopWpUEwrYD5ifhvx+sT2IjhENGfdZlFm/c43ON9erGI/wXxjq5lznnoZhf8h+rkfh2d0H9uJYlaen2Nr03rtSDPUlQvQjmxvpe/DX5vWk3Fz7e4+ZkugH/vwrHXWPI9R3pux5SuHMxqM49ODCZIygIHQ//qR2XHLu0fkRo0vuuNqDOIHcAyIrLs6HO2MS1GaQY1Iz3lY0pREqdBVq4PF8TbcXeY83lg+HKCmxbprxqWwo3KsiO3UoLwZDGo8kPuLdZZO9haHXCSGWDbs8xKqZoS2rDe14u36rM9FhuCoa0GeRhzmsCrAN1JKmL0sgeh3BZxkakO/s5dNffdL+qCzi0utB0pJkD8KV4KatY5QH0XHcER8kvXVaCq+syh5lAT8lIhqF9ZZzGZLpMDh4BLXunXMO3J04OauXJiQ0gAaajSIl7Axs93Z2tk5Z137YOpcVQim7wsR9K+knopYLpdYWrrlZZLF6qUquP0JDzHjEJjU+Jjn/XUqDgonhQ0nrTb+ooLRofw40P3T6K+ytiDRP/WLXq78nUH7eA6oglW3NFK7RjaEqF1SpW6zf3ncS86oPI8QD6b3g0AEW16t6NfnJWCk5oq19vSq98jgV5m90izlh+iab2DxkFXtNVvZx9u0mY0+U4kPh6aXn+zwOKZwEaUBdq0NNQzQg==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: sapfire-dev
