---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgA/d6b8PFPmbP+Xjv1zMXlN8j9kzkculdonvHo4tAwKylycgfr+3SwJ2HB6fsB3XWDcRP0LIQhXK6l5vU1IfMSTXzH/NOlw9Bas3Wls71N2CZvakMfoQ5TeETyAqPEwwGd2rbDEbNa5iJT5glEVtg4lwTrEZNC61LA8RsqXVfnY9YmZfIyBNI8PpRFwc3RxPFLuEIvxnGIOGVsVqO7OYts+4eaPeTIocsHeo7ByzW2sVPwCdYtvf4bk549dlXZx48JaAQpGJ3GW9mx2KqIGVKmuxQUVLhX0ufXt3I2o83KAQEp515IlfQ6wlKd2eKDu+JA8h2GWDymgKVIdiQsDBKD34N5msmKmFsJjZtxA2cp4aRHx0FOVadn/NrnER9CKFhkk8K/aVrs4chJaAbOZB0xZnbMtxh8WWhCyXgS04ev1ICtj4Z5Hus3dbwnTuZd42wWJg1NE5Jj5SZelHYZzGydq1XqSSnRrminP9b10+ChShJG9Ytk2Sa7q9LLiscYynjd385fojX9KzbFbwg2U9tnUT9b1YVoNz9ZVlPc/3O0APGIhi9Cn8O2VYVd1JC75m3hw/4v7TIQiaPQrBLUpD0vz6u7zzu4gvTUsFxoxZHCCHh3JeZazmWZjAb9PHnkPhgl8GGN+0VHOomjXfbsHZo6ARd2OI6WfSTCr/QIVki/g1CWFV3od77f6NdIaoyx06B766QLe9NwHJoVKrPMvHbbtETAFz8SKFLiyHOs1hL5CAA==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: sapfire-dev
