---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sapfire-db-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    APP_DB_PASSWORD: AgAKKTgsbr/hWXpC32n1zWiW0Tf6bs6jHHD5TbtKdcd40grryZP5Byp+IDKGHf/kYWZUqrO7d8nGVEVru+BflJKiHMpAyWP1qW8OdoYrByudoGWKIStifiZp/gMAwZpt0JT5wKkQv1Z60hpXuTnQUPuxrabhTzFT50vS8QSPWdWdqW26K5TAc3Xl0+QRyhHMM7aU53Cq4CmDhF1eoWUl0Xaqppi1OWDfr3rxB2Mct+rOT4se5tVdrpGhm8ILqkIGR7vE7TCrQRRaRV7QZVKWHqkHBCjHSoAe/77yacB0FM4Ew26qv8zBiAJg9a7IZu+da2sLB4QHOHzYN+cVKwF55JVjPfMHf6Kp8dyYK83WO/SBJPm0P7s7av4xTTKTOVbkK9+E7C52t92Ubw6xoTRw5qv4Ga5r0HbdFi/iFfDMkLbfgugJIwRZGbCAt6K1LjcoUzwHfGfunpmK8mspgEYGV0Wwu14yk17GgfjPNvZ34WJh7+5MJPQBtjB0yxPHgS6XVibtiwDMYxsZnwrit3d+1cPLfZdOvno8s4aNxgF+8ixn54tnhujValvtS+zuPRxt0Aj2iEXVP4q5ohlx5QilDG2d/BEUASDiQIXEm5Lq5T1tHYbn1pQmHr+t04ILih6QTLEPsCqaAXGDK7qWcwY3SzZ/k0UkjpraV2huKkVtgMnVy/s4Yxo4Llrl6VFrvwbnK3+utH4HsSHjSb0T0QBwXTHMGuvBRIGwO37rPcvgNFqJ3g==
  template:
    metadata:
      name: sapfire-db-credentials
      namespace: sapfire-dev
