apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sapfire-db-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    APP_DB_PASSWORD: AgBJtIgh/kMJpBiaWmfKAMg1rWu197fSBE0tUtrK0hc2JhHPqTkFA4EwBAlcHMMWth6V88GR9gjpQ5Nbh5V/lPf1UVBbhnbWUsfy3or8CHiXsUInIXTGMtyTO8mBeleuEBaICWZ6TaMplc2FbsV81Tvloo+G0C1KW1nD/pUVQDanPT+TCcMSaBI0loZ0uU6QyetZuWwqVyfvgReoS7Tbgk5Mce3uIvKF9HH/eF4qiEFMUCWyc69rXsTvh/1VJoWs+a8xsOB/0zFAWvaZ0hdZm+kuvXKZEp4NQsS1ljiTn8sty4F/Ul5D8iTHR8OtebFcIM6UgivEo7TBDkpJSOIXIhNX4P+2yPUJW/5buspG6Sldkp3WDWtfxKn2CACN5RQtJL/jkz2QM3viSAzQ9tcPtGmTdI+PQN8A+PytSSy+f+E7eTDyb/W2mJEx7Fe3E9buvA2YLAttphAoDpP7btVVLygRx4wDDbNiYOizlDDgLlYkswHyXs2GkFxBdKhIxFt7OdGcF71wZkzRzDbqIulee9gDN41+78K4iPi/k9r7uM98DFxwToVLvBXTgpkFCx1kxoiWjE7zfrIZ1ecLEiYn8KRYOtyApcy+mEdW3LpgaZUEBnpptxkQDYdo35oioY45YDw6qi68SgvcQ2UpRjQbUfx7rtE97h4eHadsG7RBNyUpiGvlBdDjf9zaBRc9OK20byLvv6L0qlIZysXsgugknYoSng==
  template:
    metadata:
      name: sapfire-db-credentials
      namespace: sapfire-dev