---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sapfire-db-credentials
  namespace: sapfire-dev
spec:
  encryptedData:
    APP_DB_PASSWORD: AgApZLk8J0xihY0hH3pU1oxsJdE9gLpCl7qYp6P5Gf/hltFJGM8zPG7VvNr8L45EltowXEMFkkvdrTh9nWOKZn8qQN6kkjF02oEeDIZC9pbr2WgH67NDXHSG3oEb7eVGaLJgw9MaEjkblwOkXf10icGJdbxGQHIcEQZifED4D8tjl3FyiY3PKGma6wUXYT8iZxsCEasZl+IsvtUJ9vrJZWVcPih92sAchLf8znZZHMb7bXu9wykNbjWk3hFKbahT4u4C4fLZq1WKKrEk8OfTVOKtVfybrtlwgkRNasFfvwXjEWBQwd6+JFLtsc3CO6L42kXaR39azMgg+UaV85h9urdZglJIeQzzH4BMmTCyh3Ml5cgoo7WWg95Vb7B354l/XCnHkVIxv7l6X0nrL67AHS3wA8RtkL4nZgI3oHkop/EOgqAZRDv4bL0EL98pvleFv6ZTsH1elMGkObeZG4yMwU7XreIYLzXyIg7pTMLYDcBn6r6mC7pPSY/Snfx3vJvUS8RQbnQpMujt582pwwSLRqcBssswW/rdRb7U5PP3ADJGsQEgULfchSrpMSvTwqsWnWDpbNchiXlkC/SjWfZjEsfhEPnbxiXNZzk6o44qeOKWAqPGQH9JzIZq3JaQHkBY/ZQ+A1G9IV6Xwm7JIBMBX7v1ugrJCGxPFKJDD77jOhl7GK0EDUY8FRnOUPmNROqqg5dTc6gd5Ne1UcdNzQi9zRSTGVgJCq91SkJj9b9qvHc8YA==
  template:
    metadata:
      name: sapfire-db-credentials
      namespace: sapfire-dev
